name: Build captions index from API

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests srt

      - name: Fetch captions via YouTube API (manual first, auto fallback)
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          YOUTUBE_HANDLE: "@blackoutapp"
        run: python scripts/fetch_captions_api.py

      - name: Show caption counts
        run: |
          echo "SRT files downloaded:" $(ls captions/*.srt 2>/dev/null | wc -l)

      - name: Build index.json
        env:
          YT_HANDLE: "@blackoutapp"
        run: python scripts/build_index_from_srt.py

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebase onto latest
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }}

      - name: Commit & push (with retry)
        run: |
          set -e
          git add public/index.json
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Update transcript index"
          for i in 1 2 3; do
            if git push origin HEAD:${{ github.ref_name }}; then
              exit 0
            fi
            echo "Push failed (attempt $i). Rebasing and retrying..."
            git pull --rebase origin ${{ github.ref_name }}
          done
          echo "Push failed after retries"
          exit 1
